"use strict"

// todo: add missing ones
export const strerror = {
    EACCES: "Permission denied",
    EADDRINUSE: "Address already in use",
    ECONNREFUSED: "Connection refused",
    ECONNRESET: "Connection reset by peer",
    EEXIST: "File already exists",
    EISDIR: "Is a directory",
    EMFILE: "Too many open files in system",
    ENOENT: "No such file or directory",
    ENOTDIR: "Not a directory",
    EPERM: "Operation not permitted",
    EPIPE: "Broken pipe",
    ETIMEDOUT: "Connection timed out",
    ENOTEMPTY: "Directory not empty",
    EROFS: "Read-only file system",
    ENOSPC: "No space left on device",
    EBADF: "Bad file descriptor",
    EINVAL: "Invalid argument",
    ENFILE: "File table overflow",
    ENOSYS: "Function not implemented",
    ELOOP: "Too many symbolic links encountered",
    ENAMETOOLONG: "Name too long",
    ENODEV: "No such device",
    ENOTSUP: "Operation not supported",
    EFAULT: "Bad address",
    EBUSY: "Resource busy or locked",
    EIO: "I/O error",
    ENXIO: "No such device or address",
    EMLINK: "Too many links",
    EHOSTUNREACH: "Host is unreachable",
    EADDRNOTAVAIL: "Address not available",
    ENETDOWN: "Network is down",
    ENETUNREACH: "Network is unreachable",
    EAFNOSUPPORT: "Address family not supported",
    EPROTONOSUPPORT: "Protocol not supported",
    EPROTOTYPE: "Protocol wrong type for socket",
    ESHUTDOWN: "Cannot send after transport endpoint shutdown",
    EHOSTDOWN: "Host is down",
    ENOPROTOOPT: "Protocol not available",
    EDOM: "Math argument out of domain of function",
    ERANGE: "Result too large",
}
